version: '3.8'

services:
  # PostgreSQL with PostGIS for tracking system testing
  postgres-tracking:
    image: postgis/postgis:15-3.3-alpine
    container_name: ready-set-tracking-db
    ports:
      - "5434:5432" # Different port to avoid conflicts
    environment:
      POSTGRES_USER: tracking_user
      POSTGRES_PASSWORD: tracking_pass
      POSTGRES_DB: ready_set_tracking
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - postgres_tracking_data:/var/lib/postgresql/data
      - ./sql/init:/docker-entrypoint-initdb.d/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U tracking_user -d ready_set_tracking"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  # Redis for real-time data caching (optional but recommended for tracking)
  redis-tracking:
    image: redis:7-alpine
    container_name: ready-set-tracking-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_tracking_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    restart: unless-stopped

  # Supabase Local Stack for testing (optional)
  supabase-studio:
    image: supabase/studio:20231123-5cbb5df
    container_name: ready-set-supabase-studio
    ports:
      - "3001:3000"
    environment:
      SUPABASE_URL: http://localhost:54321
      SUPABASE_REST_URL: http://localhost:54321/rest/v1/
      SUPABASE_ANON_KEY: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZS1kZW1vIiwicm9sZSI6ImFub24iLCJleHAiOjE5ODM4MTI5OTZ9.CRXP1A7WOeoJeXxjNni43kdQwgnWNReilDMblYTn_I0
      SUPABASE_SERVICE_KEY: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZS1kZW1vIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImV4cCI6MTk4MzgxMjk5Nn0.EGIM96RAZx35lJzdJsyH-qQwv8Hdp7fsn3W0YpN81IU
    depends_on:
      - postgres-tracking
    restart: unless-stopped

volumes:
  postgres_tracking_data:
  redis_tracking_data: 