// Shape of the user-facing changelog data file under src/data/changelog.json.
// Source of truth: src/data/changelog.json (hand-polished). Entries are
// auto-collected from commit `Changelog:` trailers and regenerated by:
//   node scripts/build-changelog.mjs

export type ChangelogChangeType = "new" | "improved" | "fixed";

export interface ChangelogChange {
  type: ChangelogChangeType;
  text: string;
}

export interface ChangelogEntry {
  version: string;
  date: string;
  title: string;
  summary: string;
  changes: ChangelogChange[];
  link?: { label: string; url: string };
}

export interface ChangelogData {
  title: string;
  subtitle: string;
  entries: ChangelogEntry[];
}
