// Shapes of the generated JSON files under src/data/.
// Source of truth: meetings/shared/tasks-board.json (workspace-level) and the
// quarterly CSV under docs/ready-set/qa/. Regenerated by:
//   node meetings/shared/build-tasks-board.mjs
//   node docs/ready-set/qa/build-qa-board.mjs

export type TaskStatus = "done" | "progress" | "open" | "new";

export interface TasksBoardColumn {
  key: TaskStatus;
  title: string;
}

export interface TasksBoardTask {
  id: string;
  status: TaskStatus;
  title: string;
  owner: string;
  source: string;
  sourceRef?: string;
  tags?: string[];
  description?: string;
  relatedQa?: string;
}

export interface TasksBoardData {
  title: string;
  subtitle: string;
  generated: string;
  sources: string[];
  columns: TasksBoardColumn[];
  owners: Record<string, string>;
  sourceLabels: Record<string, string>;
  tasks: TasksBoardTask[];
}

export type QaVerdict =
  | "PASS"
  | "PARTIAL-FAIL"
  | "FAIL"
  | "BLOCKED"
  | "IN-PROGRESS"
  | "NOT-RUN"
  | "SKIPPED"
  | "UNKNOWN";

export interface QaStep {
  step: string;
  data: string;
  expected: string;
}

export interface QaTest {
  key: string;
  summary: string;
  description: string;
  status: string;
  priority: string;
  assignee: string;
  labels: string[];
  components: string[];
  folder: string;
  notes: string;
  verdict: QaVerdict;
  steps: QaStep[];
}

export interface QaBoardData {
  source: string;
  generated: string;
  total: number;
  counts: Record<QaVerdict, number>;
  verdictOrder: QaVerdict[];
  verdictLabel: Record<QaVerdict, string>;
  tests: QaTest[];
}
